whitecube/nova-flexible-content

- src/Value/Resolver.php
> Add support for accessing data nested in JSON

- README.md
> Feature request : Using nova-page with nova-flexible-content

- resources/js/components/FormGroup.vue
> Fix missing button types in form group view

- src/Http/Middleware/InterceptFlexibleAttributes.php
- src/Http/TransformsFlexibleErrors.php
Fixes the error mentioned here https://github.com/whitecube/nova-flexible-content/issues/67
> fix exception with transformFlexibleErrors

- resources/js/components/FormField.vue
- resources/js/components/FormGroup.vue
- resources/js/group.js
Hide add layouts button when field is marked as readonly
Hide delete/order group buttons when field is marked as readonly
> Respect field readonly flag

- src/Flexible.php
We need this change to be able to send parameters in the preset class.
This package will be used for big projects, which means we can collaborate for new improvements.
Or if we can use another method, we need to know. 
Thanks for this awesome package!
> Send params for preset class

- resources/js/components/FormField.vue
dropdown list with many elements overflow to header problem fixed
> dropdown list pin changed

- README.md
Fixing a few very minor spelling errors, and grammatical issues
> Fix README typos and flow

- src/Concerns/HasFlexible.php
> Fixing #131, to allow nested json fields

- src/Value/Resolver.php
> Resolving issue #154

- src/Layouts/Layout.php
Customize duplicate and hydrate function so it works with Nova Currency field (tested for version 3.5.0).
> Fix bug on Currency field (fixed #166)

- src/Flexible.php
my locale is not "en", therefore a translation is helpfull
> localize "add layout" button

- resources/js/components/DeleteGroupModal.vue
- resources/js/components/FormGroup.vue
- resources/js/components/SearchMenu.vue
Some strings were not translatable.
> Adds more translatable strings

- src/Concerns/HasMediaLibrary.php
Hello again!
Here is my PR for the additional features on the HasMediaLibrary trait.
* I added the media autoremove behavior using the `removeCallback` method, and determing all collections by querying the database. I'm not sure if this is the best way to do it though.
* I also added a loop in the `getMediaModel` method allowing to use nested fields. Using a layout with `HasMediaLibrary` trait inside another layout requires the parent layout to use `HasMediaLibrary` too.
Let me know if I should make more changes!
> Added more features to HasMediaLibrary trait

- resources/js/components/OriginalDropMenu.vue
i was developing a package with flexible content. then i was suppose to capture add group event but i couldn't. so i added to `Nova.$emit` for this.
> add global emit

- src/Concerns/HasMediaLibrary.php
- added missing use row
- change getMediaModel method from protected to public. Cause it needs for some cases with cascade different Flexible Fields with different Layouts.
> Fixes for HasMediaLibrary trait

- src/Layouts/Layout.php
As described in #402 
It was tested on Laravel v9.34 and v9.35
> #402: Undefined property: {Layout}::$exists

- src/Layouts/Layout.php
Resolves #400 
Backport of https://github.com/whitecube/nova-flexible-content/pull/371
> PHP 8.1 warning fixes on 0.X branch

- src/Layouts/Layout.php
> Fix for RelationResolver error (Laravel v9.42.1)

- composer.json
I couldn't see any breaking changes or even updates required to the package besides simply updating `composer.json` and add support for Laravel 10.
Fixes #437
> Adding Support for Laravel 10

- src/Concerns/HasFlexible.php
> fix undefined array key warning

- composer.json
- docs/README.md
- src/Concerns/HasFlexible.php
- src/Flexible.php
- src/Http/FlexibleAttribute.php
- src/Layouts/Collection.php
- src/Layouts/Layout.php
- src/Stubs/Resolver.stub
- src/Value/FlexibleCast.php
- src/Value/Resolver.php
- src/Value/ResolverInterface.php
Few fixes in types and PHPDoc to make codebase more readable for static analysis tools (PHPStan, Psalm, IDEs, etc)
> Fix some type issues detected by Psalm

- src/Concerns/HasFlexible.php
Fixes https://github.com/whitecube/nova-flexible-content/issues/468
> Fix forceFill issue

- src/Layouts/Layout.php
Should fix the issue #464
Tested it on our own version of the package and everything seems to be working!
> Add forceFill method to Layout class
