whitecube/nova-flexible-content

src/Flexible.php, src/Http/ScopedRequest.php
Fixes methods where PHPDoc @return statements were marked as `this` but should be `$this` instead
=> Fix invalid PHPDoc @return this type statements

src/Layouts/Layout.php
In order to be able to pass all attributes as an array to include sub view, example:
```
@include('flexible-content.'. $content->name(), $content)
```
```
// flexible-content/name.blade.php
{{ $title }}
```
=> Add Arrayable interface implementation to Layout

resources/js/components/FormField.vue
As per #65 this is a simple fix, as we already have the overflow-y-auto class, so scrolling still occurs.
=> Cut overflow-hidden to remove 3 layout limitation

src/Flexible.php
As well as allowing the user to pass in multiple arguments to the addLayout function, and the layout class name as a string, allow the user to pass in a single argument of a pre-initialized layout object.
=> Allow user to pass in pre-initialized layout object to addLayout

resources/js/components/DetailField.vue, resources/js/components/DetailGroup.vue
@voidgraphics Since for an important project I really need my reported [issue](https://github.com/whitecube/nova-flexible-content/issues/113) resolved, I started to do some research and debugging. I could not identify the issue yet, but found **one part** of the problem with File fields (based on a already open [PR](https://github.com/whitecube/nova-flexible-content/pull/108)). At the moment it is not possible to download files in the detail view when they are used inside a flexible content. This is partly caused by the fact that the DetailGroup component did not receive the resourceName and resourceId until now. So the download-link was /undefined/undefined/... and subsequently Nova's _FieldDownloadController_ did not find the resource.
_Note: If you combine these small changes with the …
=> Added resource to DetailGroup Component.

resources/js/components/SearchMenu.vue, resources/sass/multiselect.scss
Put the `vue-multiselect` in the `flexible-search-menu` inside a div with the class `flexible-search-menu-multiselect` and then wrapped the SCSS in the `multiselect.scss` in a `.flexible-search-menu-multiselect` selector to avoid leaking the multiselect styles all across the Laravel Nova instance. Now they only apply to the multiselect field inside `flexible-search-menu`. This fixes #137  and provides support for `nova-multiselect-field`.
=> Scope flexible-search-menu's multiselect field SCSS (fix #137)

src/Concerns/HasFlexible.php, src/Flexible.php, src/Http/ScopedRequest.php, src/Layouts/Layout.php
For proper autocomplete. If the namespaces are relative, it can't be read correctly so it expands to ~~`\Whitecube\NovaFlexibleContent\Concerns`~~`\Whitecube\NovaFlexibleContent\Layouts\Collection` instead of just `\Whitecube\NovaFlexibleContent\Layouts\Collection`
=> Fix relative namespace in phpDoc

src/Value/Resolver.php
In #49, a check was added to support casting the flexible attribute to a
collection, in your Eloquent model. However, this check didn't actually
work as intended because the Collection class wasn't imported.
=> Import Collection

src/Concerns/HasFlexible.php
Changes:
Get the raw attributes data using the "attributes" property to prevent creating a loop.
Heres an example that will create a loop:
1. We call "flexible()" when accessing the "pages" property.
2. The "flexible()" method tries to get "pages" property directly from model,
which means "getPagesAttribute()" will be called again.
```
public function getPagesAttribute()
{
return $this->flexible('pages', ...);
}
```
=> Prevent creating a loop between model and trait.

src/Http/TransformsFlexibleErrors.php
Right now, the attributes are not translated from the validation file.
=> See the "title", "video" and "content"
With this attributes will be translated if the translation is set in validation.attributes. (example using the french locale)
=> "title" become "titre"
=> "video" become "vidéo"
=> "content" become "contenu"
=> Translate the attribute if the translation exists

src/Concerns/HasFlexible.php
This PR makes sure flexible content casting is not skipped when using this package in testing environment. Refer to #169 for more information.
**In short**
Previously the `cast` method only checked if the NovaServiceProvider was registered in order to determine if the values needed to be cast to a flexible collection.
Nova always registers the NovaServiceProvider when running in console. This caused the cast method to never actually cast the value when running PHPUnit.
This PR adds an additional check to determine if the app is running in `testing` environment to circumvent this issue.
=> Ensure flexible fields are casted in testing environment

src/Concerns/HasFlexible.php
This PR fixes the integration with the MediaLibrary.
When the layout has a single `Images` field there are no attributes:
```json
[{"key": "gCnp7d2OpddfWoMU", "layout": "gallerylayout", "attributes": []}]
```
And this `!$attritubes` check prevents such layout from the correct mapping.
=> Fix MediaLibrary integration

composer.json
Require laravel nova >=3.2.0 for method FieldCollection::filterForDetail to work
=> Require laravel nova ^3.2

src/Concerns/HasMediaLibrary.php
To solve `Call to a member function getMedia() on array`.
should use `is_a` instead of `is_subclass_of` for class checks.
it will always return false with `is_subclass_of` by check the field class. because the `$field` is not a subclass of `Ebess\AdvancedNovaMediaLibrary\Fields\Media`.
=> fix class checks with Media class

src/Flexible.php
This ensures the collection of groups doesn't contain false or corrupt values.
I'm using this package together with the [Nova Dependency Container](https://novapackages.com/packages/epartment/nova-dependency-container), in the following way:
```
NovaDependencyContainer::make([
Flexible::make('Sliding cards', 'content')
->fullWidth()
->addLayout('Sliding cards', 'sliding_cards', [
Flexible::make('Sliding cards')
->fullWidth()
->button('Voeg kaart toe')
->addLayout('Kaart', 'card', [
Text::make('Titel van de kaart'),
Text::make('Plaatje'),
Text::make('Kort tekstje erbij'),
]),
])
->limit(1),
])->dependsOn('type', StickyStoryModel::SLIDING_CARDS),
NovaDependencyContainer::make([
Flexible::make('Video', 'content')
->fullWidth()
->addLayout(StickyStoryVideo::class)
->limit(1), …
```
=> Filter falsey values from collection

src/Concerns/HasMediaLibrary.php
Next to `addMedia`, Spatie's library supports a couple of other `addMediaFrom*` methods.
I needed this one in my project, so I ported it based on your work on `addMedia`.
=> Add addMediaFromUrl to HasMediaLibrary

src/Layouts/Layout.php
I ran into some trouble where "Origin HasMedia model not found.", even though I explicitly called `setModel()`.
It turns out this was because the model property is not preserved when duplicating the Layout. 
I'm not entirely sure if this aligns with your idea for this property, so let me know if this is actually unwanted behavior. 
Come to think of it: I'm not yet sure why this duplication is necessary. Maybe you can enlighten me? 🙂
=> Preserve model when duplicating layout

src/Concerns/HasFlexible.php
That casting operator is greedy. Therefore it will cast `$item->attributes` into an array, and only _afterwards_ tack on the `?? []` operation. 
So this _might_ throw an ErrorException if the object doesn't support an `attributes` property: `Undefined property: stdClass::$attributes`.
Adding some parentheses fixes this.
=> Fix undefined property 'attributes'

src/Flexible.php
Allows user to pass in a pre-initialized resolver object. My case is as follows: I have an one-to-many relationship and I am using Flexible to create a new child resource. The layout fields are dynamic and they depend on attributes of the parent resource. The use of the custom resolver is to get/set data from/to a related entity table (related to parent also). The `$resource` argument on `public function get($resource, $attribute, $layouts)` method is an empty (child) resource when clicking the create button, so I do not have access to the parent entity. It may be possible to use the current `request()` to load the parent entity from the route params but with this change I just passing the parent entity to the resolver as constructor argument (and any other data I may need). Hope that …
=> Allow user to pass in pre-initialized resolver object to resolver method

.github/workflows/ci.yml, README.md, composer.json, docs/README.md, tests/Unit/Layouts/CollectionTest.php
At GRRR we use this package more and more. @harmenjanssen who created some PR's is a colleague of mine. To increase the quality of this package we would like to be able to write unit tests. Hopefully you're willing to accept this rather big change.
I've added PHPUnit and a workflow file to run the unit tests every time a push is made. The workflow requires a Nova license. Two secrets (`NOVA_USERNAME` and `NOVA_PASSWORD`) have to added to the repo.
=> Add PHPUnit

src/Http/FlexibleAttribute.php
Convert empty string to null (like Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull does)
Fix https://github.com/whitecube/nova-flexible-content/issues/282
=> Convert empty string to null (like Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull does)

src/Concerns/HasFlexible.php
The Flexible cast doesn't work inside Tinker, because the NovaServiceProvider is loaded. This is a suggested fix for this issue.
=> Fix Flexible cast inside Tinker

composer.json
PR allows people to upgrade to Laravel 9.
I've gone through the package and tested several functions. Additionally, we have a few sites running Laravel 9 and flexible content with no issues. Everything seems to work for Laravel 9. Nothing in the upgrade guide stood out to me for being a breaking change. Laravel 8 to 9 isn't a huge shift.
=> Laravel 9 Upgrade

resources/js/components/OriginalDropMenu.vue
If there is flexible content inside flexible content, the z-index is wrong the later button is shown over the inner scope button dropdown.
=> Fix dropdown z-index

src/Stubs/Resolver.php
Names in DocBlocks were wrong (missing leading backslash to indicate a fully qualified name)
=> Fixing fully qualified names in docblocks

src/Concerns/HasFlexible.php
`app()->runningInConsole()` solves the problem with unit tests, so we don't need this hardcoded environment check any longer. 
Additionally, if we want to use `testing` environment instead of `local` for some reason ( to check something while developing ), this env check will cause errors on nova pages with flexible fields.
=> Remove hardcoded environment check

src/Layouts/Layout.php
PHP versions before 8.0 parse the attribute syntax as a code comment and do not cause any syntax errors. Adding #[\ReturnTypeWillChange] attribute to a class method does not cause any issues, but omits the deprecation notice in PHP 8.1.
=> PHP 8 Warnings: JsonSerializable, ArrayAccess

src/Concerns/HasMediaLibrary.php
Required by `while ($model instanceof Layout)`. 
Fixes issue where sublayouts cannot be resolved to the Media model as described in https://github.com/whitecube/nova-flexible-content/pull/358.
=> Add use statement for Layout class

resources/js/components/FormField.vue, resources/js/components/FormGroup.vue
Now Nova passes a prop to fields, allowing it to behave differently in forms and in modals.
This PR receives the prop using nova mapProps mixin, and passes it to the fields in groups.
=> Field new "mode" prop.

src/Http/ScopedRequest.php
This includes the group key as a property on the ScopedRequest class.
Useful if you want to do anything with the scoped request (specifically in any of the `get{specificity}Rules` methods) within any fields that may be in the layout. Without this context there is nothing to inform which group you are currently working with (and therefore no way to create and return a `FlexibleAttribute`)
=> feat(ScopedRequest): model scope on request

src/Layouts/Layout.php
Please add this to fix the "Undefined property: Whitecube\NovaFlexibleContent\Layouts\Layout::$exists" error for nova 3 users.
=> add exits and wasrecentlycreated

src/Concerns/HasFlexible.php
#469 broke existing layouts. This PR rectifies that.
=> Fix existing layouts breaking as of 1.0.9

src/FileAdder/FileAdder.php
There was an issue with **rtrim** which removed also the last character from the `$collectionName`. 
I have multiple different disks defined inside `config/filesystems.php`.
I have a custom layout created `App\Nova\Flexible\Layouts\GalleryLayout` with the `HasMediaLibrary` trait. The name of the attribute there is `articleImage` which represents the name of the collection inside the **determineDiskName** --> `whitecube/nova-flexible-content/src/FileAdder/FileAdder.php:34`.
So the `$collectionName` together with suffix is something like: `articleImage_cTWnzJ0PsPJXzxWJ`.
After the **rtrim** result I've got: `articleImag` This caused that the **determineDiskName** method always returned the `public` disk, because such collection was not found.
The `str_replace` fixes this issue.
=> Changed rtrim to str_replace inside "determineDiskName" method

src/Layouts/Layout.php
Closes #495. 
Recent run-time error introduced with Laravel v10.40. 
I don't think it makes sense to use this feature with flexible content, so I gave it a hard-coded `false` value. It serves solely as a placeholder.
=> Add missing preventsAccessingMissingAttributes method
